const HEADER_HEIGHT = 56;
const MOBILE_NAVIGATION_HEIGHT = 76;

// Chat Bubbles
const MAX_VISIBLE_BUBBLES = 5;
const MAX_VISIBLE_BUBBLES_EXPANDED = 10;

export {
  HEADER_HEIGHT,
  MOBILE_NAVIGATION_HEIGHT,
  MAX_VISIBLE_BUBBLES,
  MAX_VISIBLE_BUBBLES_EXPANDED,
};
