import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "../components/LeftSidebar-Home/Header";

import MobileNavigation from "../components/LeftSidebar-Home/MobileNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Xoxo -media social",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="mt-14">{children}</div>
        <MobileNavigation />
      </body>
    </html>
  );
}
